apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react
          image: materialdash.azurecr.io/react:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: webappkey

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-services
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
